name: demo

on:
  push:
    branches:
    - master

jobs:
  demo:
    name: Demo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Use node
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
      env:
        DEMO: true
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        allow_empty_commit: false
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./demo-dist
