name: publish

on:
  push:
    branches:
    - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use node
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
        registry-url: https://registry.npmjs.org
    - name: Install
      run: pnpm install
    - name: Test
      run: pnpm test
    - name: Build
      run: pnpm build
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_TOKEN }}
